require File.dirname(__FILE__) + '/timetravel/interval'
require File.dirname(__FILE__) + '/timetravel/numeric'
require File.dirname(__FILE__) + '/timetravel/date'
require File.dirname(__FILE__) + '/timetravel/time'
require File.dirname(__FILE__) + '/timetravel/date_time'